### ISSUE TITLE
请问出现module 'tensorflow._api.v2.train' has no attribute 'Optimizer'怎么解决？

### ISSUE THREAD

**Issue by yourenit** [wshuyi/demo-chinese-text-binary-classification-with-bert#13]
请问出现module 'tensorflow._api.v2.train' has no attribute 'Optimizer'怎么解决？

**Comment by yourenit** [comment]
已解决

**Comment by marcocrxu** [comment]
请问下怎么解决的

**Comment by xi-mad** [comment]
import tensorflow as tf

print(tf.__version__)
!pip uninstall tensorflow==2.3.0
!pip install tensorflow==1.15.0
!pip install bert-tensorflow

run this and restart environment, and then reimport tensorflow @marcocrxu
